-- SWITCH TO THE DATABASE
\C BOOKSTORE

-- CREATE TABLE 
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
    BOOK_ID SERIAL PRIMARY KEY, 
	TITLE VARCHAR(100),
	AUTHOR VARCHAR(100),
	GENRE VARCHAR(50),
	PUBLISHED_YEAR INT ,
	PRICE DECIMAL(10,2),
	STOCK INT
);

DROP TABLE IF EXISTS CUSTOMERS ;
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID SERIAL PRIMARY KEY ,
	NAME VARCHAR(100),
	EMAIL VARCHAR(100),
	PHONE VARCHAR(15),
	CITY VARCHAR(50),
	COUNTRY VARCHAR(150)
);

DROP TABLE IF EXISTS ORDERS ;
CREATE TABLE ORDERS (
    ORDER_ID SERIAL PRIMARY KEY,
	Customer_ID INT REFERENCES Customers(Customer_ID),
    Book_ID INT REFERENCES Books(Book_ID),
    Order_Date DATE,
    Quantity INT,
    Total_Amount NUMERIC(10, 2)
);

SELECT * FROM Books;
SELECT * FROM Customers;
SELECT * FROM Orders;

-- Import Data into Books Table
COPY Books(Book_ID, Title, Author, Genre, Published_Year, Price, Stock) 
FROM  'C:\Users\ashwanirai\Desktop\SQL Project on Online Book Store\Books.csv'
CSV HEADER;

-- Import Data into Customers Table
COPY Customers(Customer_ID, Name, Email, Phone, City, Country) 
FROM 'C:\Users\ashwanirai\Desktop\SQL Project on Online Book Store\Customers.csv' 
CSV HEADER;

-- Import Data into Orders Table
COPY Orders(Order_ID, Customer_ID, Book_ID, Order_Date, Quantity, Total_Amount) 
FROM 'C:\Users\ashwanirai\Desktop\SQL Project on Online Book Store\Orders.csv' 
CSV HEADER;

--BASIC QUERY 

-- 1) Retrieve all books in the "Fiction" genre:

SELECT * FROM BOOKS
WHERE Genre='Fiction';

-- 2) Find books published after the year 1950:
SELECT * FROM BOOKS 
WHERE Published_year>1950;

-- 3) List all customers from the Canada:
SELECT * FROM CUSTOMERS
WHERE country='Canada';

--4)Show orders placed in November 2023 :
SELECT *  FROM ORDERS 
WHERE ORDER_DATE BETWEEN '2023-11-01' AND '2023-11-30' ;

--5) RETRIEVE THE TOTAL STOCK OF BOOKS AVAILABLE : 
SELECT SUM(STOCK) AS TOTAL_STOCK FROM BOOKS ;

--6) FIND THE MOST EXPENSIVE BOOK : 
SELECT * FROM BOOKS 
ORDER BY PRICE DESC 
LIMIT 1;

--7) SHOW ALL CUSTOMERS WHO ORDERED MORE THAN 1 QUANTITY OF A BOOK: 
SELECT * FROM ORDERS 
WHERE QUANTITY > 1 ;

--8) RETRIEVE ALL ORDERS WHERE THE TOTAL AMOUNT EXCEEDS $20:
SELECT * FROM ORDERS
WHERE TOTAL_AMOUNT > 20 ;

--9) LIST ALL THE GENRE AVAILABLE IN THE BOOKS TABLES : 
SELECT DISTINCT GENRE FROM BOOKS ;

--10) FIND THE BOOK WITH THE LOWEST STOCK : 
SELECT *FROM BOOKS 
ORDER BY STOCK ASC LIMIT  ;

--11) CALCULATE THE TOTAL REVENUE GENERATE FROM ALL ORDERS : 
SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE FROM ORDERS;


-- ADVANCE QUESTION 

--1) RETRIEVE THE TOTAL NUMBER OF BOOKS SOLD FOR EACH GENRE: 
SELECT B.GENRE , SUM(O.QUANTITY) AS TOTAL_NUMBER_OF_BOOK_SOLD
FROM ORDERS  O 
JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID
GROUP BY B.GENRE

--2) FIND THE AVERAGE PRICE OF BOOKS IN THE 'FANTASY'GENRE :
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM BOOKS
WHERE GENRE = 'Fantasy';

--3) LIST CUSTOMERS WHO HAVE PLACED AT LEAST 2 ORDER :
SELECT CUSTOMER_ID ,COUNT(ORDER_ID) AS NUMBER_OF_ORDERS FROM ORDERS 
GROUP BY CUSTOMER_ID
HAVING COUNT(ORDER_ID) >= 2  ;

SELECT O.CUSTOMER_ID , C.NAME, COUNT(O.ORDER_ID) 
FROM ORDERS O 
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID 
GROUP BY O.CUSTOMER_ID , C.NAME 
HAVING COUNT(O.ORDER_ID) >= 2


-- 4) FIND THE MOST FREQUENTLY ORDERED BOOK:
SELECT BOOK_ID ,COUNT(ORDER_ID) AS MOST_ORDERED_BOOK 
FROM ORDERS GROUP BY BOOK_ID ORDER BY COUNT(ORDER_ID) DESC;

SELECT O.BOOK_ID , B.TITLE , COUNT(O.ORDER_ID) 
FROM ORDERS O 
JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID 
GROUP BY O.BOOK_ID , B.BOOK_ID 
ORDER BY COUNT(O.ORDER_ID) DESC LIMIT 1 ;

-- 5) SHOW THE TOP 3 MOST EXPENSIVE BOOKS OF 'FANTASY' GENRE: 
SELECT * FROM BOOKS 
WHERE GENRE = 'Fantasy' 
ORDER BY PRICE DESC 
LIMIT 3;

--6) RETRIEVE THE TOTAL QUANTITY OF BOOKS SOLD BY EACH AUTHOR: 
SELECT  B.AUTHOR , SUM(O.QUANTITY)  AS NUMBER_OF_BOOK_SOLD
FROM ORDERS O
JOIN BOOKS B ON O.BOOK_ID = B.BOOK_ID 
GROUP BY B.AUTHOR ;

--7) LIST THE CITIES WHERE CUSTOMERS WHO SPENT OVER $30 ARE LOCATION :
SELECT * FROM CUSTOMERS;
SELECT * FROM  ORDERS;
SELECT  DISTINCT C.CITY , total_amount 
FROM ORDERS O
JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID 
where  O.TOTAL_AMOUNT >30 ;

-- 8) Find the customer who spent the most on orders:
SELECT c.customer_id, c.name, SUM(o.total_amount) AS Total_Spent
FROM orders o
JOIN customers c ON o.customer_id=c.customer_id
GROUP BY c.customer_id, c.name
ORDER BY Total_spent Desc LIMIT 1;


--9) Calculate the stock remaining after fulfilling all orders:

SELECT b.book_id, b.title, b.stock, COALESCE(SUM(o.quantity),0) AS Order_quantity,  
	b.stock- COALESCE(SUM(o.quantity),0) AS Remaining_Quantity
FROM books b
LEFT JOIN orders o ON b.book_id=o.book_id
GROUP BY b.book_id ORDER BY b.book_id;